before_install:
- rvm install 2.3.1

language: ruby
rvm:
  - 2.3.1

script:
  - bundle exec middleman build

deploy:
  provider: s3
  access_key_id:
    secure: iwMwoMkf538cyOQKowv+FwqtbiAnviyAJdxpfgwfqDlQd3dLSPuK4MuyUD96hwzR2Uix36H+9Iyo2WEmovXkH+S+BjzmLBGemC/LNUl2L+9AQHc9pW9ilA2Tvv0nd/ZXOhzvBkM/UFc1ucSahy81kqcXAtjv4IZzgQDbC3HIwBM0+sO9Kx2o+6LhKndp61ZgyVHg2hBYKg9r3W8BXC71Tm2jcZnySWn4exLgJ4WOEQ0hzsQDGlzLDNZoXC0mkQVktXzn3eB9gjpJgR7szM6IxDP5YoJbkunGeKjbw8cmHjjiRNhtAprhGYmphOESDRDEWxX/RIRZF9DTELtcfiH0dU5jUWqYgRTYgFVOa0V0zoFW5bOom/KW8KpkY2cOFUtUdhoLrdGyp8VdlEPEJl05YFUXDDGgCm+3EMjw8uj95q3Hq/DiRuj36TdhWTSftUbj2pAZyBK8YqxaMAZPdWD1y2zJXmZ4GKQ+FWENyXP2W9imkZRmzXrD0COBSy9qkqQvZWnhrDXFMoCvTO2iNmNnGI18KldCrnTgfkQ9ZWotTdZKO4G3A0UlU/rHQkv0ryukiYcFOMX3VIiF6p06fuEQEo6r98vlad2w+xZpfRnZUMq3JEZIjP0fjzyXC0YfziwP4jNT7QX/13ulMYlbLCFehRPCu8+9nrgoXzrTqPEVGYw=
  secret_access_key:
    secure: Pz4/u2/yWAKdfhLwlJMa4il3bGE54AD/Q7g68WXVptL1b0LJF8uvjSf4Mua002Vxk4eDGxASjSkTAl98YgHuyVWj8aoY/hSzV2B6jmehupNzoEFgx6YaRgJ7/qLkxDEKe7ai7Idn7OebFkeQVUh/fNRnpF/J1nnKY9z1efaCTo79TAerW8lbnanHQEGTzqj1K5C+viBotaB2aPDSws6VTYSR5WAeTDOMZBfoUS/S43udJ9B8E/6uMmNrTArmkP15m71SgFGu+RIau/N0EbNSm5e6IxeBzCTZHZxPMJyg0tgYxac+JVLezlh8jlO6JhcyknXbFJW/doLqOt85ZwuMrbbWridwE4WiEs7xv/6C8Ru/hHjxNPmisw47sQbmB1hQl/I2CSATkT5Z5G1mNxERJZqoP7rUjeyzuPvzbrXlbgnp9BJxiTx3Io3L3bERZ7OeOtHn4rnt0/0uZfT9ys0QR7Lhn3vSDM/4SQaamw2KY2P0+ejudqw+bW010FYIP0xad+3kKN2O6iQ8xSeT0DKql7zD+s2n0CTe100w5WxbpeDYxZOFs/ialA8unOLKASH+dvThdzy5BwAdbXh4pBUzmkgoNB7Q2iws7KLRjkHkpUh8zy8CgmDGYuIxubM+TIgeVEpkaAoCM6TAOsVIrn9LAwjsdqBFRRIqt8sqYU1A2RE=
  bucket:
    secure: QQTzMuCmVaJnr8OM6khVeuvt3NzC2qFfD46VLPmEup64c7nfsL5lU1sncsGaGEz3Whk8MW/sXOvHvSGU6MrJHFeBCnoL7EafbJ6vpJTQ63p+Mpe8f5FHK5jF4c3Ui+xgt/+ZdhDlT/eZd8UhPC8SEVXqUKRfAqmZ8EUfsDwpz3zw7IuTcJvLRDQu62DP2W6vPkfW3Qt7xaMmFqXk1LE3EylyL9Iwith3yA4kQIyNQBOTYMw6zEAtnG2eNhkywWiYACSO8F657lj2mkA5KQtnT4kV42g/tsvDZqLn68EdI2GCMIg0xuNrvKGtQLVlzDrcKrQUsGnl0TT/bwILXdE1x10+pxo1fHjipGHKrZkWZ+KifsLCpjLgZGvKJalKQn3B0kP9AOOR4eE8YVBQGaCiNYsgNP/Hszyob0MFf5ijmA1gcESAY2IhWtPhRopXDicxXsYolWO7qCRK1nd1ZByidU2cx/yalO7/XxYNyJnkT5h/mPGjcSpWpuKYUqr8KEWIe+cfEyT6/Wlq+8t2dvEoboYp4M7KpoLmpD3+/ygCWWCWATKVu5Csawbz6k42BjYgX+L/za/wnKa4z56X4YfGc9hNbVn3DtSyt0IVueKrzLIkrWVVdzFEWjDznDmZZP/v5ToU3ibq+A+JZ45Covuh2iX4kreknfxqSeNr/HGbxHY=
  skip_cleanup: true
  local_dir: build
  acl: public_read

notifications:
  webhooks:
  - https://webhooks.datocms.com/5854778df6f7956d99ff/deploy-results
